# Generated by Django 5.0.1 on 2024-01-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('user_name', models.CharField(db_index=True, max_length=50)),
                ('post_delay', models.IntegerField(default=1)),
            ],
        ),
    ]
