# Generated by Django 5.0.1 on 2024-01-10 11:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0004_copy_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='channel_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
