# Generated by Django 5.0.1 on 2024-01-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsModel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsModel',
        ),
    ]
