# Generated by Django 5.0.1 on 2024-01-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0006_usermodel_request_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='request_link',
        ),
    ]
