# Generated by Django 5.0.1 on 2024-01-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsModel', '0008_alter_postsmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='caption',
        ),
    ]
