# Generated by Django 5.0.1 on 2024-01-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsModel', '0009_remove_postsmodel_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='author',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='tags',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
