# Generated by Django 5.0.1 on 2024-01-18 16:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('user_name', models.CharField(db_index=True, max_length=50)),
                ('post_delay', models.IntegerField(default=1)),
                ('channel_id', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None)),
            ],
        ),
    ]
