# Generated by Django 5.0.1 on 2024-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ChannelModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('channels', models.ManyToManyField(blank=True, to='ChannelModel.channelmodel')),
            ],
        ),
    ]
