# Generated by Django 5.0.1 on 2024-01-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsModel', '0003_postsmodel_media_type_alter_postsmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='media_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('GIF', 'Gif'), ('VIDEO', 'Video')], default='PHOTO', max_length=5),
        ),
    ]
