# Generated by Django 5.0.1 on 2024-01-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostsModel', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='test',
        ),
    ]
