# Generated by Django 5.0.1 on 2024-01-18 16:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField()),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_admins', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None)),
                ('request_link', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_delay', models.IntegerField(default=15)),
                ('delay_point', models.DateTimeField(blank=True, null=True)),
                ('last_post', models.DateTimeField(blank=True, null=True)),
                ('caption_template', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('channel_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.usermodel')),
            ],
        ),
    ]
