# Generated by Django 5.0.1 on 2024-01-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel_id',
            field=models.CharField(),
        ),
    ]
