# Generated by Django 5.0.1 on 2024-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0002_channelmodel_posts_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='enhance_links',
            field=models.BooleanField(default=True),
        ),
    ]
