# Generated by Django 5.0.1 on 2024-01-10 18:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0003_channelmodel_request_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='channel_admins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, null=True, size=None),
        ),
    ]
