# Generated by Django 5.0.1 on 2024-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0011_channelmodel_last_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='caption_template',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
