# Generated by Django 5.0.1 on 2024-01-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0008_remove_channelmodel_delay_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='delay_point',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
