# Generated by Django 5.0.1 on 2024-01-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0009_channelmodel_delay_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmodel',
            name='delay_point',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
