# Generated by Django 5.0.1 on 2024-01-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserModel', '0002_usermodel_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_admins', models.JSONField(blank=True, null=True)),
                ('channel_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserModel.usermodel')),
            ],
        ),
    ]
