# Generated by Django 5.0.1 on 2024-01-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0002_alter_channelmodel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='request_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
