# Generated by Django 5.0.1 on 2024-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0004_alter_channelmodel_channel_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='channel_delay',
            field=models.IntegerField(default=15),
        ),
    ]
