# Generated by Django 5.0.1 on 2024-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0005_channelmodel_channel_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
