# Generated by Django 5.0.1 on 2024-01-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChannelModel', '0007_channelmodel_delay_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmodel',
            name='delay_point',
        ),
    ]
